[variables]
NODE_VERSION = "18.20.4"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18"]
cmds = ["node --version", "npm --version"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.start]
cmd = "npm start"